### ISSUE TITLE
淘宝领金币.js这个里面怎么去掉 充话费拿金币

### ISSUE THREAD

**Issue by changer2222** [clousky2020/auto.js-#1]
需要把"充话费拿金币"跳过，不执行，要不然一直在那儿循环了.不能执行下去

**Comment by clousky2020** [comment]
代码已更新，我的解决方式是，定义一个变量，代表点击第几个去完成的图标，碰到这个页面，变量+1，跳过这个图标。

**Comment by changer2222** [comment]
赞.
任务里面，卡到了"邀请好友一起玩庄园“，我只好注掉"去添加”，要不然也是和上面一样。
是不是也可以和上面的处理方式一样，变量+1就不让再进了
